clf ; taille = 20 ; plot(1,1,'.') ; grid on
X_DS = [0 1] ; Y_DS = [0 1]; %Where we want the annotation on the plot
[X_NFU,Y_NFU] = ds2nfu(X_DS,Y_DS); %Scaled to the real window units that annotation requires in input
a = annotation('arrow', ...
           'LineStyle','none', ...
           'HeadStyle','cback3', ...
           'HeadLength',taille,'HeadWidth',taille, ...
           'Units','normalized', ...
           'X',X_NFU,'Y',Y_NFU); hold on

%test
[xtest,ytest] = ds2nfu([x(end-1) x(end)],[y(end-1) y(end)]);
annotation('arrow', ...
           'LineStyle','none', ...
           'HeadStyle','cback3', ...
           'HeadLength',taille,'HeadWidth',taille, ...
           'Units','normalized', ...
           'X',X_NFU,'Y',Y_NFU);